version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - scraper

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    networks:
      - scraper

  app:
    build:
      context: .
    links:
      - mongo:mongo
    networks:
      - scraper

volumes:
  mongo-data:

networks:
  scraper:
